"""Role-level expectation blocks, keyed by the ``level`` setting's allowed values."""

LEVEL_CONTEXT: dict[str, str] = {
    "intern": (
        "Internship candidate (current student or recent graduate)\n\n"
        "What to look for:\n"
        "  - Strong fundamentals: relevant coursework, personal projects, prior internships\n"
        "  - Curiosity signals: open-source contributions, hackathons, side projects\n"
        "  - Ability to learn: projects that show growth from start to finish\n"
        "  - Communication: clear explanation of their own role in team projects\n\n"
        "What to flag:\n"
        "  - Padding: listing every course taken or irrelevant work history\n"
        "  - Vague project descriptions: 'used Python' without saying what they built\n"
        "  - No technical depth: copy-paste projects without original work\n"
        "  - Overreach: claiming 'led architecture' as a student (unlikely)\n\n"
        "Structure expectations: one page; Education first, then projects and any "
        "experience. Projects should be real and used by someone — not class "
        "assignments or tutorial walkthroughs.\n\n"
        "Score calibration: a 7-8 intern resume shows strong projects, clear personal "
        "contribution, and genuine technical curiosity. Professional experience is not "
        "expected — depth over breadth matters more."
    ),
    "junior": (
        "Junior engineer (0-2 years professional experience)\n\n"
        "What to look for:\n"
        "  - Real production contributions: features shipped to actual users\n"
        "  - Growing independence: work that started guided and became self-directed\n"
        "  - Fundamentals applied at work: testing, code review, debugging in a real codebase\n"
        "  - Trajectory: evidence they absorbed feedback and took on more over time\n\n"
        "What to flag:\n"
        "  - Only school projects: no signal of contributing to a production codebase\n"
        "  - Task-oriented language: 'completed tickets', 'fixed bugs as assigned'\n"
        "  - No outcomes: work described without what it did for users or the team\n"
        "  - Inflated claims: ownership of systems a junior would not credibly own alone\n\n"
        "Structure expectations: one page, with Experience above Education.\n\n"
        "Score calibration: a 7-8 junior resume shows real production contributions with "
        "some measurable outcomes and visibly growing scope. Big architectural impact is "
        "not expected."
    ),
    "mid": (
        "Mid-level engineer (3-5 years experience)\n\n"
        "What to look for:\n"
        "  - Independent delivery: shipped features end-to-end without hand-holding\n"
        "  - Ownership: specific systems or areas they were responsible for\n"
        "  - Technical depth: meaningful use of technologies, not just listing them\n"
        "  - Collaboration: worked across teams or functions on non-trivial efforts\n\n"
        "What to flag:\n"
        "  - Task-oriented language: 'completed tickets', 'followed instructions'\n"
        "  - Missing scope: no sense of how large or complex their projects were\n"
        "  - No metrics: achievements without numbers, scale, or outcomes\n"
        "  - Stagnation: same responsibilities for 3+ years without growth\n\n"
        "Structure expectations: one page; Experience first, Education near the bottom "
        "with the GPA removed.\n\n"
        "Score calibration: a 7-8 mid-level resume shows consistent independent delivery "
        "with measurable impact and growing scope. The candidate can be trusted to own a "
        "feature area."
    ),
    "senior": (
        "Senior engineer (6+ years experience)\n\n"
        "What to look for:\n"
        "  - Architecture thinking: system design decisions, trade-offs, migrations\n"
        "  - Mentoring: growing other engineers through code review, guidance, sponsorship\n"
        "  - Cross-team influence: driving initiatives that span multiple teams\n"
        "  - Business impact: technical work tied to revenue, cost, or user outcomes\n\n"
        "What to flag:\n"
        "  - IC-only framing: all 'I did X' with no evidence of unblocking others\n"
        "  - No technical depth: buzzwords without describing architectural decisions\n"
        "  - Vague leadership: 'mentored juniors' with no specifics on how or outcomes\n"
        "  - Missing judgment: no evidence of making trade-off decisions\n"
        "  - Impact gap: lots of work described but no connection to business results\n\n"
        "Structure expectations: one to two pages; earlier roles condensed to a line or "
        "two; Education at the bottom; a brief summary is acceptable at this level (and "
        "only at this level).\n\n"
        "Score calibration: a 7-8 senior resume shows a clear track record of technical "
        "leadership, mentoring, and business-aligned impact. The candidate raises the bar "
        "for those around them."
    ),
}
